package com.hahahardware.hahahardware;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Charge implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "id")
	private java.lang.String id;
	@org.kie.api.definition.type.Label(value = "amount")
	private java.lang.Double amount;
	@org.kie.api.definition.type.Label(value = "customerId")
	private java.lang.String customerId;
	@org.kie.api.definition.type.Label(value = "isPaid")
	private java.lang.Boolean isPaid;
	@org.kie.api.definition.type.Label(value = "paymentDate")
	private java.time.LocalDateTime paymentDate;

	public Charge() {
	}

	public java.lang.String getId() {
		return this.id;
	}

	public void setId(java.lang.String id) {
		this.id = id;
	}

	public java.lang.Double getAmount() {
		return this.amount;
	}

	public void setAmount(java.lang.Double amount) {
		this.amount = amount;
	}

	public java.lang.String getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(java.lang.String customerId) {
		this.customerId = customerId;
	}

	public java.lang.Boolean getIsPaid() {
		return this.isPaid;
	}

	public void setIsPaid(java.lang.Boolean isPaid) {
		this.isPaid = isPaid;
	}

	public java.time.LocalDateTime getPaymentDate() {
		return this.paymentDate;
	}

	public void setPaymentDate(java.time.LocalDateTime paymentDate) {
		this.paymentDate = paymentDate;
	}

	public Charge(java.lang.String id, java.lang.Double amount,
			java.lang.String customerId, java.lang.Boolean isPaid,
			java.time.LocalDateTime paymentDate) {
		this.id = id;
		this.amount = amount;
		this.customerId = customerId;
		this.isPaid = isPaid;
		this.paymentDate = paymentDate;
	}

}