package com.hahahardware.hahahardware;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Customer implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "id")
	private java.lang.String id;
	@org.kie.api.definition.type.Label(value = "name")
	private java.lang.String name;
	@org.kie.api.definition.type.Label(value = "surname")
	private java.lang.String surname;
	@org.kie.api.definition.type.Label(value = "streetName")
	private java.lang.String streetName;
	@org.kie.api.definition.type.Label(value = "streetNumber")
	private java.lang.String streetNumber;
	@org.kie.api.definition.type.Label(value = "postalCode")
	private java.lang.String postalCode;
	@org.kie.api.definition.type.Label(value = "city")
	private java.lang.String city;
	@org.kie.api.definition.type.Label(value = "country")
	private java.lang.String country;

	public Customer() {
	}

	public java.lang.String getId() {
		return this.id;
	}

	public void setId(java.lang.String id) {
		this.id = id;
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.String getSurname() {
		return this.surname;
	}

	public void setSurname(java.lang.String surname) {
		this.surname = surname;
	}

	public java.lang.String getStreetName() {
		return this.streetName;
	}

	public void setStreetName(java.lang.String streetName) {
		this.streetName = streetName;
	}

	public java.lang.String getStreetNumber() {
		return this.streetNumber;
	}

	public void setStreetNumber(java.lang.String streetNumber) {
		this.streetNumber = streetNumber;
	}

	public java.lang.String getPostalCode() {
		return this.postalCode;
	}

	public void setPostalCode(java.lang.String postalCode) {
		this.postalCode = postalCode;
	}

	public java.lang.String getCity() {
		return this.city;
	}

	public void setCity(java.lang.String city) {
		this.city = city;
	}

	public java.lang.String getCountry() {
		return this.country;
	}

	public void setCountry(java.lang.String country) {
		this.country = country;
	}

	public Customer(java.lang.String id, java.lang.String name,
			java.lang.String surname, java.lang.String streetName,
			java.lang.String streetNumber, java.lang.String postalCode,
			java.lang.String city, java.lang.String country) {
		this.id = id;
		this.name = name;
		this.surname = surname;
		this.streetName = streetName;
		this.streetNumber = streetNumber;
		this.postalCode = postalCode;
		this.city = city;
		this.country = country;
	}

}