package com.hahahardware.hahahardware;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Document implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "id")
	private java.lang.String id;
	@org.kie.api.definition.type.Label(value = "title")
	private java.lang.String title;
	@org.kie.api.definition.type.Label(value = "text")
	private java.lang.String text;
	@org.kie.api.definition.type.Label(value = "customerId")
	private java.lang.String customerId;
	@org.kie.api.definition.type.Label(value = "chargeId")
	private java.lang.String chargeId;
	@org.kie.api.definition.type.Label(value = "documentType")
	private java.lang.String documentType;
	@org.kie.api.definition.type.Label(value = "serviceType")
	private java.lang.String serviceType;

	public Document() {
	}

	public java.lang.String getId() {
		return this.id;
	}

	public void setId(java.lang.String id) {
		this.id = id;
	}

	public java.lang.String getTitle() {
		return this.title;
	}

	public void setTitle(java.lang.String title) {
		this.title = title;
	}

	public java.lang.String getText() {
		return this.text;
	}

	public void setText(java.lang.String text) {
		this.text = text;
	}

	public java.lang.String getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(java.lang.String customerId) {
		this.customerId = customerId;
	}

	public java.lang.String getChargeId() {
		return this.chargeId;
	}

	public void setChargeId(java.lang.String chargeId) {
		this.chargeId = chargeId;
	}

	public java.lang.String getDocumentType() {
		return this.documentType;
	}

	public void setDocumentType(java.lang.String documentType) {
		this.documentType = documentType;
	}

	public java.lang.String getServiceType() {
		return this.serviceType;
	}

	public void setServiceType(java.lang.String serviceType) {
		this.serviceType = serviceType;
	}

	public Document(java.lang.String id, java.lang.String title,
			java.lang.String text, java.lang.String customerId,
			java.lang.String chargeId, java.lang.String documentType,
			java.lang.String serviceType) {
		this.id = id;
		this.title = title;
		this.text = text;
		this.customerId = customerId;
		this.chargeId = chargeId;
		this.documentType = documentType;
		this.serviceType = serviceType;
	}

}