package com.hahahardware.hahahardware;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.xml.bind.annotation.XmlRootElement
public class Feedback implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("id")
	private java.lang.String id;
	@org.kie.api.definition.type.Label("overallRating")
	private java.lang.Integer overallRating;
	@org.kie.api.definition.type.Label("timeRating")
	private java.lang.Integer timeRating;
	@org.kie.api.definition.type.Label("serviceQualityRating")
	private java.lang.Integer serviceQualityRating;
	@org.kie.api.definition.type.Label("communicationQualityRating")
	private java.lang.Integer communicationQualityRating;
	@org.kie.api.definition.type.Label("text")
	private java.lang.String text;
	@org.kie.api.definition.type.Label("serviceType")
	private java.lang.String serviceType;

	@org.kie.api.definition.type.Label(value = "timestamp")
	private java.lang.String timestamp;

	public Feedback() {
	}

	public java.lang.String getId() {
		return this.id;
	}

	public void setId(java.lang.String id) {
		this.id = id;
	}

	public java.lang.Integer getOverallRating() {
		return this.overallRating;
	}

	public void setOverallRating(java.lang.Integer overallRating) {
		this.overallRating = overallRating;
	}

	public java.lang.Integer getTimeRating() {
		return this.timeRating;
	}

	public void setTimeRating(java.lang.Integer timeRating) {
		this.timeRating = timeRating;
	}

	public java.lang.Integer getServiceQualityRating() {
		return this.serviceQualityRating;
	}

	public void setServiceQualityRating(java.lang.Integer serviceQualityRating) {
		this.serviceQualityRating = serviceQualityRating;
	}

	public java.lang.Integer getCommunicationQualityRating() {
		return this.communicationQualityRating;
	}

	public void setCommunicationQualityRating(
			java.lang.Integer communicationQualityRating) {
		this.communicationQualityRating = communicationQualityRating;
	}

	public java.lang.String getText() {
		return this.text;
	}

	public void setText(java.lang.String text) {
		this.text = text;
	}

	public java.lang.String getServiceType() {
		return this.serviceType;
	}

	public void setServiceType(java.lang.String serviceType) {
		this.serviceType = serviceType;
	}

	public java.lang.String getTimestamp() {
		return this.timestamp;
	}

	public void setTimestamp(java.lang.String timestamp) {
		this.timestamp = timestamp;
	}

	public Feedback(java.lang.String id, java.lang.Integer overallRating,
			java.lang.Integer timeRating,
			java.lang.Integer serviceQualityRating,
			java.lang.Integer communicationQualityRating,
			java.lang.String text, java.lang.String serviceType,
			java.lang.String timestamp) {
		this.id = id;
		this.overallRating = overallRating;
		this.timeRating = timeRating;
		this.serviceQualityRating = serviceQualityRating;
		this.communicationQualityRating = communicationQualityRating;
		this.text = text;
		this.serviceType = serviceType;
		this.timestamp = timestamp;
	}

}