package com.hahahardware.hahahardware;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.xml.bind.annotation.XmlRootElement
public class newFeedbackSignal implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "feedbackId")
	private java.lang.String feedbackId;

	public newFeedbackSignal() {
	}

	public java.lang.String getFeedbackId() {
		return this.feedbackId;
	}

	public void setFeedbackId(java.lang.String feedbackId) {
		this.feedbackId = feedbackId;
	}

	public newFeedbackSignal(java.lang.String feedbackId) {
		this.feedbackId = feedbackId;
	}

}