package com.hahahardware.hahahardware;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.xml.bind.annotation.XmlRootElement
public class PartType implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("id")
	private java.lang.String id;
	@org.kie.api.definition.type.Label("name")
	private java.lang.String name;

	@org.kie.api.definition.type.Label(value = "isInOffer")
	private java.lang.Boolean isInOffer;

	@org.kie.api.definition.type.Label(value = "reorderPoint")
	private java.lang.Integer reorderPoint;

	public PartType() {
	}

	public java.lang.String getId() {
		return this.id;
	}

	public void setId(java.lang.String id) {
		this.id = id;
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.Boolean getIsInOffer() {
		return this.isInOffer;
	}

	public void setIsInOffer(java.lang.Boolean isInOffer) {
		this.isInOffer = isInOffer;
	}

	public java.lang.Integer getReorderPoint() {
		return this.reorderPoint;
	}

	public void setReorderPoint(java.lang.Integer reorderPoint) {
		this.reorderPoint = reorderPoint;
	}

	public PartType(java.lang.String id, java.lang.String name,
			java.lang.Boolean isInOffer, java.lang.Integer reorderPoint) {
		this.id = id;
		this.name = name;
		this.isInOffer = isInOffer;
		this.reorderPoint = reorderPoint;
	}

}