package com.hahahardware.hahahardware;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Part implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "id")
	private java.lang.String id;
	@org.kie.api.definition.type.Label(value = "stockId")
	private java.lang.String stockId;
	@org.kie.api.definition.type.Label(value = "partTypeId")
	private java.lang.String partTypeId;

	public Part() {
	}

	public java.lang.String getId() {
		return this.id;
	}

	public void setId(java.lang.String id) {
		this.id = id;
	}

	public java.lang.String getStockId() {
		return this.stockId;
	}

	public void setStockId(java.lang.String stockId) {
		this.stockId = stockId;
	}

	public java.lang.String getPartTypeId() {
		return this.partTypeId;
	}

	public void setPartTypeId(java.lang.String partTypeId) {
		this.partTypeId = partTypeId;
	}

	public Part(java.lang.String id, java.lang.String stockId,
			java.lang.String partTypeId) {
		this.id = id;
		this.stockId = stockId;
		this.partTypeId = partTypeId;
	}

}