package com.hahahardware.hahahardware;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Product implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "id")
	private java.lang.String id;
	@org.kie.api.definition.type.Label(value = "warrantyTill")
	private java.time.LocalDateTime warrantyTill;
	@org.kie.api.definition.type.Label(value = "serialNumber")
	private java.lang.String serialNumber;
	@org.kie.api.definition.type.Label(value = "productionDate")
	private java.time.LocalDateTime productionDate;
	@org.kie.api.definition.type.Label(value = "stockId")
	private java.lang.String stockId;
	@org.kie.api.definition.type.Label(value = "purchaseDate")
	private java.time.LocalDateTime purchaseDate;
	@org.kie.api.definition.type.Label(value = "saleDate")
	private java.time.LocalDateTime saleDate;
	@org.kie.api.definition.type.Label(value = "customerId")
	private java.lang.String customerId;
	@org.kie.api.definition.type.Label(value = "productTypeId")
	private java.lang.String productTypeId;

	public Product() {
	}

	public java.lang.String getId() {
		return this.id;
	}

	public void setId(java.lang.String id) {
		this.id = id;
	}

	public java.time.LocalDateTime getWarrantyTill() {
		return this.warrantyTill;
	}

	public void setWarrantyTill(java.time.LocalDateTime warrantyTill) {
		this.warrantyTill = warrantyTill;
	}

	public java.lang.String getSerialNumber() {
		return this.serialNumber;
	}

	public void setSerialNumber(java.lang.String serialNumber) {
		this.serialNumber = serialNumber;
	}

	public java.time.LocalDateTime getProductionDate() {
		return this.productionDate;
	}

	public void setProductionDate(java.time.LocalDateTime productionDate) {
		this.productionDate = productionDate;
	}

	public java.lang.String getStockId() {
		return this.stockId;
	}

	public void setStockId(java.lang.String stockId) {
		this.stockId = stockId;
	}

	public java.time.LocalDateTime getPurchaseDate() {
		return this.purchaseDate;
	}

	public void setPurchaseDate(java.time.LocalDateTime purchaseDate) {
		this.purchaseDate = purchaseDate;
	}

	public java.time.LocalDateTime getSaleDate() {
		return this.saleDate;
	}

	public void setSaleDate(java.time.LocalDateTime saleDate) {
		this.saleDate = saleDate;
	}

	public java.lang.String getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(java.lang.String customerId) {
		this.customerId = customerId;
	}

	public java.lang.String getProductTypeId() {
		return this.productTypeId;
	}

	public void setProductTypeId(java.lang.String productTypeId) {
		this.productTypeId = productTypeId;
	}

	public Product(java.lang.String id, java.time.LocalDateTime warrantyTill,
			java.lang.String serialNumber,
			java.time.LocalDateTime productionDate, java.lang.String stockId,
			java.time.LocalDateTime purchaseDate,
			java.time.LocalDateTime saleDate, java.lang.String customerId,
			java.lang.String productTypeId) {
		this.id = id;
		this.warrantyTill = warrantyTill;
		this.serialNumber = serialNumber;
		this.productionDate = productionDate;
		this.stockId = stockId;
		this.purchaseDate = purchaseDate;
		this.saleDate = saleDate;
		this.customerId = customerId;
		this.productTypeId = productTypeId;
	}

}