package com.hahahardware.hahahardware;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.xml.bind.annotation.XmlRootElement
public class Product implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("id")
	private java.lang.String id;
	@org.kie.api.definition.type.Label("warrantyTill")
	private String warrantyTill;
	@org.kie.api.definition.type.Label("serialNumber")
	private java.lang.String serialNumber;
	@org.kie.api.definition.type.Label("productionDate")
	private String productionDate;
	@org.kie.api.definition.type.Label("stockId")
	private java.lang.String stockId;
	@org.kie.api.definition.type.Label("purchaseDate")
	private String purchaseDate;
	@org.kie.api.definition.type.Label("saleDate")
	private String saleDate;
	@org.kie.api.definition.type.Label("customerId")
	private java.lang.String customerId;
	@org.kie.api.definition.type.Label("productTypeId")
	private java.lang.String productTypeId;

	public Product() {
	}

	public java.lang.String getId() {
		return this.id;
	}

	public void setId(java.lang.String id) {
		this.id = id;
	}

	public java.lang.String getSerialNumber() {
		return this.serialNumber;
	}

	public void setSerialNumber(java.lang.String serialNumber) {
		this.serialNumber = serialNumber;
	}

	public java.lang.String getStockId() {
		return this.stockId;
	}

	public void setStockId(java.lang.String stockId) {
		this.stockId = stockId;
	}

	public java.lang.String getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(java.lang.String customerId) {
		this.customerId = customerId;
	}

	public java.lang.String getProductTypeId() {
		return this.productTypeId;
	}

	public void setProductTypeId(java.lang.String productTypeId) {
		this.productTypeId = productTypeId;
	}

	public java.lang.String getWarrantyTill() {
		return this.warrantyTill;
	}

	public void setWarrantyTill(java.lang.String warrantyTill) {
		this.warrantyTill = warrantyTill;
	}

	public java.lang.String getProductionDate() {
		return this.productionDate;
	}

	public void setProductionDate(java.lang.String productionDate) {
		this.productionDate = productionDate;
	}

	public java.lang.String getPurchaseDate() {
		return this.purchaseDate;
	}

	public void setPurchaseDate(java.lang.String purchaseDate) {
		this.purchaseDate = purchaseDate;
	}

	public java.lang.String getSaleDate() {
		return this.saleDate;
	}

	public void setSaleDate(java.lang.String saleDate) {
		this.saleDate = saleDate;
	}

	public Product(java.lang.String id, java.lang.String warrantyTill,
			java.lang.String serialNumber, java.lang.String productionDate,
			java.lang.String stockId, java.lang.String purchaseDate,
			java.lang.String saleDate, java.lang.String customerId,
			java.lang.String productTypeId) {
		this.id = id;
		this.warrantyTill = warrantyTill;
		this.serialNumber = serialNumber;
		this.productionDate = productionDate;
		this.stockId = stockId;
		this.purchaseDate = purchaseDate;
		this.saleDate = saleDate;
		this.customerId = customerId;
		this.productTypeId = productTypeId;
	}

}