package com.hahahardware.hahahardware;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.xml.bind.annotation.XmlRootElement
public class ProductSales implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "itemsPurchased")
	private java.lang.Integer itemsPurchased;
	@org.kie.api.definition.type.Label(value = "itemsSold")
	private java.lang.Integer itemsSold;

	public ProductSales() {
	}

	public java.lang.Integer getItemsPurchased() {
		return this.itemsPurchased;
	}

	public void setItemsPurchased(java.lang.Integer itemsPurchased) {
		this.itemsPurchased = itemsPurchased;
	}

	public java.lang.Integer getItemsSold() {
		return this.itemsSold;
	}

	public void setItemsSold(java.lang.Integer itemsSold) {
		this.itemsSold = itemsSold;
	}

	public ProductSales(java.lang.Integer itemsPurchased,
			java.lang.Integer itemsSold) {
		this.itemsPurchased = itemsPurchased;
		this.itemsSold = itemsSold;
	}

}