package com.hahahardware.hahahardware;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ProductType implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "id")
	private java.lang.String id;
	@org.kie.api.definition.type.Label(value = "name")
	private java.lang.String name;
	@org.kie.api.definition.type.Label(value = "price")
	private java.lang.Double price;
	@org.kie.api.definition.type.Label(value = "discount")
	private java.lang.Double discount;
	@org.kie.api.definition.type.Label(value = "description")
	private java.lang.String description;
	@org.kie.api.definition.type.Label(value = "category")
	private java.lang.String category;

	public ProductType() {
	}

	public java.lang.String getId() {
		return this.id;
	}

	public void setId(java.lang.String id) {
		this.id = id;
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.Double getPrice() {
		return this.price;
	}

	public void setPrice(java.lang.Double price) {
		this.price = price;
	}

	public java.lang.Double getDiscount() {
		return this.discount;
	}

	public void setDiscount(java.lang.Double discount) {
		this.discount = discount;
	}

	public java.lang.String getDescription() {
		return this.description;
	}

	public void setDescription(java.lang.String description) {
		this.description = description;
	}

	public java.lang.String getCategory() {
		return this.category;
	}

	public void setCategory(java.lang.String category) {
		this.category = category;
	}

	public ProductType(java.lang.String id, java.lang.String name,
			java.lang.Double price, java.lang.Double discount,
			java.lang.String description, java.lang.String category) {
		this.id = id;
		this.name = name;
		this.price = price;
		this.discount = discount;
		this.description = description;
		this.category = category;
	}

}