package com.hahahardware.hahahardware;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.xml.bind.annotation.XmlRootElement
public class StockStats implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "currentStock")
	private java.lang.Integer currentStock;

	public StockStats() {
	}

	public java.lang.Integer getCurrentStock() {
		return this.currentStock;
	}

	public void setCurrentStock(java.lang.Integer currentStock) {
		this.currentStock = currentStock;
	}

	public StockStats(java.lang.Integer currentStock) {
		this.currentStock = currentStock;
	}

}